require 'fog/libvirt'
require 'inspec'
require 'inspec/libvirt/version'
require 'resources/libvirt/libvirt_base'
require 'resources/libvirt/libvirt_domain'
require 'resources/libvirt/libvirt_network'
require 'resources/libvirt/libvirt_volume'
